CREATE TABLE IF NOT EXISTS jenis_unit (
  id INT PRIMARY KEY,
  name VARCHAR(128),
  create_by VARCHAR(32),
  create_date TIMESTAMP
);

INSERT INTO
  jenis_unit (id, name, create_by, create_date)
VALUES
  (2,'PAKET','SYSTEM',NULL),
  (20,'KM','SYSTEM',NULL),
  (21,'PAKET','SYSTEM',NULL),
  (22,'PROYEK','SYSTEM',NULL),
  (23,'PILOT AREA','SYSTEM',NULL),
  (24,'PACKAGE','SYSTEM',NULL),
  (25,'WELL','SYSTEM',NULL),
  (38,'DRILLING PACKAGE','SYSTEM',NULL),
  (27,'SUB PAKET','SYSTEM',NULL),
  (28,'KEGIATAN','SYSTEM',NULL),
  (29,'BOR','SYSTEM',NULL),
  (30,'3D','SYSTEM',NULL),
  (31,'G&G','SYSTEM',NULL),
  (32,'2D','SYSTEM',NULL),
  (33,'PAKET SEISMIK','SYSTEM',NULL),
  (34,'OTHERS','SYSTEM',NULL),
  (35,'GF','SYSTEM',NULL),
  (36,'PROJECT','SYSTEM',NULL),
  (37,'HOLE','SYSTEM',NULL),
  (0,'SUMUR','SYSTEM',NULL),
  (1,'KEGIATAN','SYSTEM',NULL),
  (40,'STUDI','SYSTEM',NULL),
  (41,'KM2','SYSTEM',NULL);
